version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:16.0-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user123
      - POSTGRES_DB=test_db
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready
      timeout: 10s
      retries: 6

  # mysql:
  #   container_name: mysql
  #   image: mysql:8.0-debian
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root123
  #     - MYSQL_USER=user
  #     - MYSQL_PASSWORD=user123
  #     - MYSQL_DATABASE=test_db
  #   ports:
  #     - "3306:3306"
  #   healthcheck:
  #     test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
  #     timeout: 5s
  #     retries: 12

  sql-seed:
    container_name: sql-seed
    build:
      context: .
    image: sql-seed:compose
    volumes:
      - ./sql/postgres/migrations:/migrations:ro
      - ./sql/postgres/data:/data:ro
    environment:
      - DB_DRIVER=postgres
      - DB_DSN=user:user123@postgres:5432/test_db?sslmode=disable
      - MIGRATIONS_PATH=/migrations
      - DATA_PATH=/data
    depends_on:
      postgres:
        condition: service_healthy
      # mysql:
      #   condition: service_healthy
