name: CI Pipeline

on:
  push:
    branches:
      - main
      - hotfix/**
      - develop
      - feature/**
      - bugfix/**
  workflow_dispatch:

jobs:
  test:
    name: Test Runner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Run Tests
        run: go test -race -v ./...
  build:
    name: Build Runner
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Run Build
        run: go build -v ./...
